.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH MENULIBRE "1" "January 2014" "menulibre 2.0" "User Commands"
.SH NAME
menulibre \- advanced fd.o compliant menu editor
.SH DESCRIPTION
menulibre is an easy to use FreeDesktop.org-compliant menu editor. All fields specified in the FreeDesktop.org Desktop Entry and Menu specifications are available to quickly update. Additionally, menulibre provides an editor for the launcher actions used by applications such as Unity and Plank.
.SH SYNOPSIS
.B menulibre
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show debug messages
.SH "SEE ALSO"
The full documentation for
.B menulibre
is maintained online at
.URL "http://wiki.smdavis.us/doku.php?id=menulibre-docs" "the authors documentation portal" "."
.SH BUGS
No known bugs.
.SH AUTHOR
Sean Davis (smd.seandavis@gmail.com)