.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH MENULIBRE "1" "March 2018" "menulibre 2.2" "User Commands"
.SH NAME
menulibre \- advanced fd.o compliant menu editor
.SH DESCRIPTION
menulibre is an easy to use FreeDesktop.org-compliant menu editor. All fields specified in the FreeDesktop.org Desktop Entry and Menu specifications are available to quickly update. Additionally, menulibre provides an editor for the launcher actions used by applications such as Unity and Plank.
.SH SYNOPSIS
.B menulibre
[\fI\,options\/\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show debug messages
.TP
\fB\-b\fR, \fB\-\-headerbar\fR
Use headerbar layout (client side decorations)
.TP
\fB\-t\fR, \fB\-\-toolbar\fR
Use toolbar layout (server side decorations)
.SH "SEE ALSO"
The full documentation for
.B menulibre
is maintained online at
.URL "https://github.com/bluesabre/menulibre/wiki" "the MenuLibre Wiki" "."
.SH BUGS
Please report any bugs found at
.URL "https://github.com/bluesabre/menulibre/issues" "GitHub" "."
.SH AUTHOR
Sean Davis (sean@bluesabre.org)
