.\" Manpage for menulibre-menu-validate.
.TH menulibre-menu-validate "1" "January 2018" "menulibre 2.1" "menulibre-menu-validate man page"
.SH NAME
menulibre-menu-validate \- display GMenu debug output
.SH SYNOPSIS
menulibre-menu-validate
.SH DESCRIPTION
menulibre-menu-validate is intended as a convenient way to access 
GMenu's debugging output on stderr, which exposes information about 
invalid desktop files, without doing strange hacks on menulibre's own 
stderr
.SH OPTIONS
menulibre-menu-validate does not take any options.
.SH SEE ALSO
menulibre(1)
.SH BUGS
No known bugs.
.SH AUTHOR
OmegaPhil (OmegaPhil@startmail.com)
