name: Sync Launchpad issues to GitHub
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/track-lp-issues.yaml'
      - '.github/lpbugtracker.py'
  schedule:
    - cron: '0 22 * * *'

jobs:
  add-lp-issues:
    name: Sync Launchpad issues to GitHub bug tracker
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3.1.0
      - name: Install Python 3
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install launchpadlib
      - name: Mirror GitHub bugs from Launchpad
        id: getlpbugs
        run: |
          python .github/lpbugtracker.py

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
